# Generated by Django 6.0.7 on 2026-09-27 16:30

import apps.courses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonprogress_watched_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.BinaryField()),
                ('content_type', models.CharField(default='application/pdf', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'stored upload',
                'verbose_name_plural': 'stored uploads',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=apps.courses.storage.DatabaseUploadStorage(), upload_to='sop_documents/'),
        ),
    ]
