# Generated by Django 6.0.7 on 2026-09-27 18:14

import apps.courses.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_storedupload_alter_lesson_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=apps.courses.storage.DatabaseVideoStorage(), upload_to='lesson_videos/'),
        ),
    ]
