# Generated by Django 6.0.7 on 2026-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_staffuser_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Non-Teaching Staff'), ('hod', 'Head of Department'), ('admin', 'Super Admin')], default='staff', max_length=20),
        ),
    ]
